language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - pypy
install:
  - pip install -r tools/test-requires --use-mirrors
  - pip install coveralls
  - python setup.py install
script: nosetests --coverage
after_success: coveralls
notifications:
  email:
    - john.vrbanac@linux.com
